# Jupyter test

In [4]:
using Random

In [7]:
rng = MersenneTwister(4649)
;

In [14]:
for i = 1:10
   println(rand(rng))
end

0.8302726923357793
0.8981989045571834
0.8887151146146874
0.8675236106732578
0.9769321273755327
0.13814865922690878
0.7827438431829681
0.11373377018672715
0.12171499431513988
0.06297168474654158


In [6]:
N, M = 2, 4
reshape(collect((i + 2*j for j in 1:M for i in 1:N)), N, M)

2×4 Array{Int64,2}:
 3  5  7   9
 4  6  8  10

In [38]:
a = zeros(4)
b = copy(a)

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [39]:
pointer(a)

Ptr{Float64} @0x0000000130683e00

In [40]:
pointer(b)

Ptr{Float64} @0x0000000130683fc0

In [41]:
b[1] = 100

100

In [42]:
a

4-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0

In [20]:
module My

struct Point
    x::Int
    y::Int
end

function Point(x)
    return Point(x, 2*x)
end

function Point()
    return Point(0, 0)
end

end

Main.My

In [21]:
methods(My.Point)

# 4 methods for type constructor:
[1] Main.My.Point() in Main.My at In[20]:12
[2] Main.My.Point(x::Int64, y::Int64) in Main.My at In[20]:4
[3] Main.My.Point(x) in Main.My at In[20]:8
[4] Main.My.Point(x, y) in Main.My at In[20]:4

In [22]:
p = My.Point()

Main.My.Point(0, 0)

In [9]:
methods(Point)

# 1 method for generic function "Point":
[1] Point(x) in Main at In[8]:1

In [1]:
using BenchmarkTools

x = zeros(100)
y = zeros(100)

function test_f(x, y)
     x += y
end

@benchmark test_f(x, y)

BenchmarkTools.Trial: 
  memory estimate:  896 bytes
  allocs estimate:  1
  --------------
  minimum time:     70.084 ns (0.00% GC)
  median time:      75.993 ns (0.00% GC)
  mean time:        89.716 ns (5.99% GC)
  maximum time:     842.431 ns (70.46% GC)
  --------------
  samples:          10000
  evals/sample:     977

In [2]:
function test_f2(x, y)
     x .+= y
end

@benchmark test_f2(x, y)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     26.374 ns (0.00% GC)
  median time:      28.405 ns (0.00% GC)
  mean time:        31.012 ns (0.00% GC)
  maximum time:     147.199 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     993