# Jupyter test

In [1]:
using Random
using BenchmarkTools

In [19]:
N = 100

θ0 = 0.111
spins = [(cos(x), sin(x), 0.0) for x in rand(Float64[θ0, θ0+2π/3, θ0-2π/3], N)]

function compute_m_120degrees2(spins)
    cos_sum = sum([cos(3*atan(x[2], x[1])) for x in spins])
    sin_sum = sum([sin(3*atan(x[2], x[1])) for x in spins])
    (cos_sum^2 + sin_sum^2)/length(spins)^2
end

compute_m_120degrees(spins)

0.9999999999999997

In [8]:
spins = [(cos(x), sin(x), 0.0) for x in rand(Float64[0.0, 2π/3, -2π/3], N)]

100-element Array{Tuple{Float64,Float64,Float64},1}:
 (1.0, 0.0, 0.0)
 (-0.4999999999999998, 0.8660254037844387, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (1.0, 0.0, 0.0)
 (1.0, 0.0, 0.0)
 (1.0, 0.0, 0.0)
 (1.0, 0.0, 0.0)
 (1.0, 0.0, 0.0)
 (1.0, 0.0, 0.0)
 (1.0, 0.0, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, 0.8660254037844387, 0.0)
 ⋮
 (-0.4999999999999998, 0.8660254037844387, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, 0.8660254037844387, 0.0)
 (1.0, 0.0, 0.0)
 (-0.4999999999999998, 0.8660254037844387, 0.0)
 (1.0, 0.0, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, 0.8660254037844387, 0.0)
 (-0.4999999999999998, -0.8660254037844387, 0.0)
 (-0.4999999999999998, 0.8660254037844387, 0.0)

In [20]:
@benchmark compute_m_120degrees2(spins)

BenchmarkTools.Trial: 
  memory estimate:  1.77 KiB
  allocs estimate:  3
  --------------
  minimum time:     4.471 μs (0.00% GC)
  median time:      4.931 μs (0.00% GC)
  mean time:        5.482 μs (0.32% GC)
  maximum time:     95.249 μs (92.39% GC)
  --------------
  samples:          10000
  evals/sample:     7

In [25]:
module My

function add_data!(x, y)
    x += y
end

function add_data!(x, y::Array{T,I}) where {T, I}
    x .+= y
end

function add_data!(x::Vector{T}, y::Base.Generator{I,F}) where {T, I, F}
    for (i, y_) in zip(eachindex(x), y)
        x[i] += y_
    end
end

end

Main.My

In [20]:
x = zeros(10)
y = zeros(10)
@benchmark My.add_data!(x, y)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     22.499 ns (0.00% GC)
  median time:      23.232 ns (0.00% GC)
  mean time:        25.636 ns (0.00% GC)
  maximum time:     92.391 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     995

In [28]:
y = (1 for i in 1:10)
x = zeros(10)
My.add_data!(x, y)
x

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [29]:
?...

search: ...



```
...
```

The "splat" operator, `...`, represents a sequence of arguments. `...` can be used in function definitions, to indicate that the function accepts an arbitrary number of arguments. `...` can also be used to apply a function to a sequence of arguments.

# Examples

```jldoctest
julia> add(xs...) = reduce(+, xs)
add (generic function with 1 method)

julia> add(1, 2, 3, 4, 5)
15

julia> add([1, 2, 3]...)
6

julia> add(7, 1:100..., 1000:1100...)
111107
```


In [51]:
f(x) = 2*x

xvec = ones(10)
#for i in 1:10
#    xvec[i] = f(xvec[i])
#end
f.(xvec)

10-element Array{Float64,1}:
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0
 2.0

In [53]:
collect(1/xvec)

1×10 Array{Float64,2}:
 0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1  0.1

In [54]:
xvec

10-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [32]:
function f(x, y)
    x .+= y
    #for i in 1:4
    #    x[i] += y[i]
    #end
end
@benchmark f(x, y)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     20.358 ns (0.00% GC)
  median time:      22.218 ns (0.00% GC)
  mean time:        25.522 ns (0.00% GC)
  maximum time:     134.235 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     996

In [20]:
module My

struct Point
    x::Int
    y::Int
end

function Point(x)
    return Point(x, 2*x)
end

function Point()
    return Point(0, 0)
end

end

Main.My

In [21]:
methods(My.Point)

# 4 methods for type constructor:
[1] Main.My.Point() in Main.My at In[20]:12
[2] Main.My.Point(x::Int64, y::Int64) in Main.My at In[20]:4
[3] Main.My.Point(x) in Main.My at In[20]:8
[4] Main.My.Point(x, y) in Main.My at In[20]:4

In [22]:
p = My.Point()

Main.My.Point(0, 0)

In [9]:
methods(Point)

# 1 method for generic function "Point":
[1] Point(x) in Main at In[8]:1

In [1]:
using BenchmarkTools

x = zeros(100)
y = zeros(100)

function test_f(x, y)
     x += y
end

@benchmark test_f(x, y)

BenchmarkTools.Trial: 
  memory estimate:  896 bytes
  allocs estimate:  1
  --------------
  minimum time:     70.084 ns (0.00% GC)
  median time:      75.993 ns (0.00% GC)
  mean time:        89.716 ns (5.99% GC)
  maximum time:     842.431 ns (70.46% GC)
  --------------
  samples:          10000
  evals/sample:     977

In [2]:
function test_f2(x, y)
     x .+= y
end

@benchmark test_f2(x, y)

BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     26.374 ns (0.00% GC)
  median time:      28.405 ns (0.00% GC)
  mean time:        31.012 ns (0.00% GC)
  maximum time:     147.199 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     993